create table ppmsdm.ppms_sect_spc_chart(
 update_id number(10,0) not null, 
 monitor_grp varchar2(40 char) not null, 
 fab_name varchar2(10 char), 
 fab_id varchar2(2 char) not null, 
 sect_cd varchar2(10 char) not null, 
 monitor_catg varchar2(20 char) not null, 
 monitor_type varchar2(10 char) not null, 
 spc_grp_name varchar2(20 char), 
 spc_grp_no number(10,0) default '0' not null, 
 spc_cht_name varchar2(20 char), 
 spc_cht_no number(10,0) default '0' not null, 
 spc_cht_type number(10,0) default '0' not null, 
 spc_data_type varchar2(1 char) not null, 
 spc_proc_step_seq varchar2(9 char), 
 spc_meas_step_seq varchar2(9 char), 
 chart_disp_seq number(10,0) default '0' not null, 
 tight_spec_high float(126), 
 tight_spec_low float(126), 
 warn_action varchar2(10 char), 
 warn_enable varchar2(1 char), 
 warn_user_list varchar2(250 char), 
 enable_flag varchar2(1 char) not null, 
 update_dt date, 
 update_user varchar2(12 char), 
 site_prfl_type varchar2(6 char), 
 item_name varchar2(30 char), 
 dcop_mfld_id varchar2(20 char), 
 item_unit varchar2(25 char), 
 ctrl_method varchar2(45 char), 
 point_count number(10,0) default '600', 
 review_days number(10,0), 
 raw_data_item_name varchar2(30 char), 
 phase_id varchar2(10 char), 
 pre_meas_step_seq varchar2(9 char), 
 post_meas_step_seq varchar2(9 char), 
 pre_item_name varchar2(30 char), 
 post_item_name varchar2(30 char), 
 constraint primary_10 primary key (
    update_id, monitor_grp, fab_id, sect_cd, monitor_catg, monitor_type, spc_grp_no, spc_cht_no, spc_cht_type, spc_data_type, chart_disp_seq, enable_flag
 )
 ENABLE
)
